import { isApprovedReviewUrl } from './review-policy.js';
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const esc = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const metrics = {
 rva:['Replay valid-action rate','RVA',1],ova:['Rollout valid-action rate','OVA',1],f1:['Action F1','F1',1],accuracy:['Action accuracy','Acc.',1],dmJsd:['Decision-mix JSD','DM-JSD',-1],te:['Trajectory error','TE',-1],pf:['Population fidelity','PF',1],ctr:['Click-through rate error','ΔCTR',-1],acr:['Add-to-cart rate error','ΔACR',-1],tJsd:['Terminal-state JSD','T-JSD',-1]
};
const keys=Object.keys(metrics);
const levels=[
 ['REPLAY + ROLLOUT','Can the environment execute the action?','Check whether each output can be parsed into an action that is executable in the current state.',[['RVA ↑','Valid-action rate under replay'],['OVA ↑','Valid-action rate under rollout']]],
 ['REPLAY','The same state. The same next decision?','Give the simulator the real state at every step, then compare its next action with the recorded human decision.',[['F1 ↑','Agreement on the action type'],['Accuracy ↑','Action and target agreement']]],
 ['ROLLOUT','Does the journey behave like a real one?','Measure realistic decision patterns after product visits and the number of actions in each session.',[['DM-JSD ↓','Decision mix after item-page visits'],['TE ↓','Error in mean actions per session']]],
 ['ROLLOUT','Does individuality survive at scale?','Group users by historical behavior, then compare simulated and real behavior within each group: session dynamics, action patterns, and product preferences.',[['PF ↑','Personalized population fidelity']]],
 ['ROLLOUT','Do the outcomes match real shopping behavior?','Compare aggregate click and add-to-cart rates and the distribution of final session outcomes.',[['ΔCTR / ΔACR ↓','Count-based rate errors'],['T-JSD ↓','Terminal-outcome divergence']]]
];
const state={session:9,step:3,playing:false,timer:null,track:'single',modality:'all',metric:'dmJsd',annotation:'home-lighting'};
let site,trajectories,results,lastTrigger;
function toast(text){const el=$('.toast');el.textContent=text;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,3500);}
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function openDialog(dialog){lastTrigger=document.activeElement;dialog.showModal();}
function showImage(src,alt,caption){$('#full-image').src=src;$('#full-image').alt=alt;$('#image-caption').textContent=caption;openDialog($('#image-dialog'));}
function showInfo(title,content,eyebrow='RESEARCH PREVIEW'){$('#dialog-title').textContent=title;$('#dialog-eyebrow').textContent=eyebrow;$('#dialog-content').innerHTML=content;openDialog($('#info-dialog'));}
function safeUrl(url){if(!url)return null;try{const parsed=new URL(url,location.href);if(site?.reviewMode==='double-blind'&&parsed.origin!==location.origin&&!isApprovedReviewUrl(parsed.href))return null;return ['https:','http:'].includes(parsed.protocol)?parsed.href:null;}catch{return null;}}
$('.menu-toggle').addEventListener('click',()=>{const open=$('.menu-toggle').getAttribute('aria-expanded')!=='true';$('.menu-toggle').setAttribute('aria-expanded',String(open));$('.menu-toggle').setAttribute('aria-label',open?'Close navigation':'Open navigation');$('#main-nav').classList.toggle('open',open);});
$$('#main-nav a').forEach(a=>a.addEventListener('click',()=>{$('#main-nav').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');$('.menu-toggle').setAttribute('aria-label','Open navigation');}));
$$('dialog').forEach(dialog=>{dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{const b=dialog.getBoundingClientRect();if(event.target===dialog&&(event.clientX<b.left||event.clientX>b.right||event.clientY<b.top||event.clientY>b.bottom))dialog.close();});dialog.addEventListener('close',()=>lastTrigger?.focus());});
const observer=new IntersectionObserver(entries=>entries.filter(e=>e.isIntersecting).forEach(entry=>$$('#main-nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+entry.target.id))),{rootMargin:'-20% 0px -55% 0px'});
$$('main section[id]').forEach(section=>observer.observe(section));
function renderLevel(index){const level=levels[index];$$('[data-level]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.level===index)));$('#level-mode').textContent=level[0];$('#level-badge').textContent='L'+index;$('#level-question').textContent=level[1];$('#level-description').textContent=level[2];$('#level-metrics').innerHTML=level[3].map(([name,desc])=>`<div><strong>${esc(name)}</strong><p>${esc(desc)}</p></div>`).join('');}
$$('[data-level]').forEach(b=>b.addEventListener('click',()=>renderLevel(+b.dataset.level)));renderLevel(2);
function session(){return trajectories.sessions.find(s=>s.session===state.session);}
function stop(){clearInterval(state.timer);state.timer=null;state.playing=false;$('#play-keyframes').innerHTML='Play keyframes <span aria-hidden="true">▷</span>';$('#play-keyframes').setAttribute('aria-pressed','false');}
function renderTrajectory(){
 const current=session(),step=current.steps.find(s=>s.step===state.step);
 const titles={9:['Brow tint & eye cream','Two products, two add-to-cart actions.'],10:['A return visit','Explore a makeup primer sample, then return to the feed.'],11:['A later decision','Eyeshadow exploration, a logged Buy action, and more browsing.']};
 $$('[data-session]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.session===state.session)));
 $('#trajectory-title').textContent=titles[state.session][0];$('#trajectory-description').textContent=titles[state.session][1];$('#step-count').textContent=current.steps.length+' recorded steps';
 $('#timeline').innerHTML=current.steps.map(s=>`<li><button data-step="${s.step}" ${s.step===state.step?'aria-current="step"':''} aria-label="Step ${s.step}: ${esc(s.action)}${s.product?', '+esc(s.product):''}${s.image?', presentation frame available':''}"><span class="step-index">${String(s.step).padStart(2,'0')}</span><span>${esc(s.action)}</span>${s.product?`<span class="step-product">${esc(s.product)}</span>`:''}${s.image?'<span class="frame-dot" aria-hidden="true"></span>':''}</button></li>`).join('');
 $('#explorer-image').hidden=!step.image;$('#missing-frame').hidden=!!step.image;$('#expand-observation').disabled=!step.image;
 if(step.image){$('#explorer-image').src=step.image;$('#explorer-image').alt=`English reconstruction: session ${state.session}, step ${step.step}, ${step.product}`;$('#observation-caption').textContent=`Pre-action observation · Session ${state.session} · Step ${step.step}`;}else{$('#missing-step').textContent=String(step.step).padStart(2,'0');$('#observation-caption').textContent=`Recorded action: ${step.action} · No English frame`;}
 $('#keyframe-count').textContent=current.steps.filter(s=>s.image).length+' available frames';$('#previous-step').disabled=state.step===1;$('#next-step').disabled=state.step===current.steps.length;
}
$('#timeline').addEventListener('click',e=>{const b=e.target.closest('[data-step]');if(b){stop();state.step=+b.dataset.step;renderTrajectory();}});
$$('[data-session]').forEach(b=>b.addEventListener('click',()=>{stop();state.session=+b.dataset.session;state.step=session().steps.find(s=>s.image).step;renderTrajectory();}));
$('#next-step').addEventListener('click',()=>{stop();state.step=Math.min(session().steps.length,state.step+1);renderTrajectory();});
$('#previous-step').addEventListener('click',()=>{stop();state.step=Math.max(1,state.step-1);renderTrajectory();});
$('#next-frame').addEventListener('click',()=>{stop();const frames=session().steps.filter(s=>s.image);state.step=(frames.find(s=>s.step>state.step)||frames[0]).step;renderTrajectory();});
$('#expand-observation').addEventListener('click',()=>{stop();const step=session().steps.find(s=>s.step===state.step);if(step.image)showImage(step.image,$('#explorer-image').alt,`Session ${state.session} · Step ${step.step} · English presentation reconstruction, with rescaled display prices.`);});
$('#play-keyframes').addEventListener('click',()=>{if(state.playing)return stop();const frames=trajectories.sessions.flatMap(s=>s.steps.filter(t=>t.image).map(t=>({session:s.session,step:t.step})));let index=frames.findIndex(s=>s.session===state.session&&s.step===state.step);state.playing=true;$('#play-keyframes').innerHTML='Pause keyframes <span aria-hidden="true">Ⅱ</span>';$('#play-keyframes').setAttribute('aria-pressed','true');state.timer=setInterval(()=>{index=(index+1)%frames.length;state.session=frames[index].session;state.step=frames[index].step;renderTrajectory();},2400);});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
function rankedRows(){return results[state.track].filter(r=>state.modality==='all'||r.modality===state.modality).toSorted((a,b)=>(b.metrics[state.metric]-a.metrics[state.metric])*metrics[state.metric][2]||a.method.localeCompare(b.method));}
function renderLeaderboard(){
 const rows=rankedRows(),all=results[state.track],best=Object.fromEntries(keys.map(k=>[k,Math[metrics[k][2]===1?'max':'min'](...all.map(r=>r.metrics[k]))]));
 $$('[data-track]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.track===state.track)));
 let previous,rank;
 $('#leaderboard-body').innerHTML=rows.map((r,i)=>{if(r.metrics[state.metric]!==previous)rank=i+1;previous=r.metrics[state.metric];return `<tr class="${r.method==='OPTD'?'optd-row':''}"><td>${String(rank).padStart(2,'0')}</td><td>${esc(r.method)}</td><td><span class="modality-tag ${r.modality==='GUI'?'gui':''}">${r.modality}</span></td>${keys.map(k=>`<td class="${r.metrics[k]===best[k]?'best ':''}${k===state.metric?'sorted-metric':''}" title="${esc(metrics[k][0])}${r.metrics[k]===best[k]?' · Best in this setting':''}">${r.metrics[k].toFixed(k==='te'?2:4)}</td>`).join('')}</tr>`;}).join('');
 $$('#results-table thead th').forEach((cell,i)=>{if(i>=3){const selected=keys[i-3]===state.metric;cell.classList.toggle('sorted-metric',selected);cell.removeAttribute('aria-sort');if(selected)cell.setAttribute('aria-sort',metrics[state.metric][2]===1?'descending':'ascending');}});
 $('#ranking-note').textContent=`${rows.length} methods · Ranked by ${metrics[state.metric][1]} (${metrics[state.metric][2]===1?'higher':'lower'} is better)`;
}
$$('[data-track]').forEach(b=>b.addEventListener('click',()=>{state.track=b.dataset.track;renderLeaderboard();}));
$('#modality-filter').addEventListener('change',e=>{state.modality=e.target.value;renderLeaderboard();});
$('#ranking-metric').addEventListener('change',e=>{state.metric=e.target.value;renderLeaderboard();});
$('#download-results').addEventListener('click',()=>{const csv=[['setting','method','modality',...keys].join(','),...rankedRows().map(r=>[state.track,r.method,r.modality,...keys.map(k=>r.metrics[k])].join(','))].join('\n');download(`userarena-${state.track}-${state.modality}.csv`,csv,'text/csv;charset=utf-8');toast('Downloaded the currently filtered paper results.');});
function annotation(){return {src:`assets/annotation/${state.annotation}.png`,alt:state.annotation==='home-lighting'?'English A/B annotation interface for the home and lighting example':'English source-blinded A/B shopping trajectory annotation interface'};}
$$('[data-annotation]').forEach(b=>b.addEventListener('click',()=>{state.annotation=b.dataset.annotation;$$('[data-annotation]').forEach(a=>a.setAttribute('aria-pressed',String(a===b)));const img=annotation();$('#annotation-image').src=img.src;$('#annotation-image').alt=img.alt;}));
function openAnnotation(){const img=annotation();showImage(img.src,img.alt,'Source-blinded A/B interface · English presentation copy. This gallery does not collect annotation judgments.');}
$('#view-annotation').addEventListener('click',openAnnotation);$('#annotation-image-button').addEventListener('click',openAnnotation);
const resources={code:{key:'codeUrl',title:'Code & evaluation',body:'The public code repository has not been connected yet. The planned release will provide environment tools and the evaluation implementation.',details:['Replay and rollout evaluation','Single-session and cross-session settings','Metrics across L0–L4']},dataset:{key:'datasetUrl',title:'The UserArena dataset',body:'The public dataset link will appear here when the release is available. The benchmark described in the paper contains:',details:['64,729 sessions from 11,010 users','566,102 products and 577,670 actions','Step-aligned context and linked cross-session histories']},environment:{key:'environmentUrl',title:'Enter the environment',body:'The hosted interactive environment is not available in this preview. You can already inspect selected observations and recorded action sequences in the trajectory explorer.',details:['Feed navigation and product exploration','Product details, reviews, and shopping actions','Replay and rollout interfaces for simulator evaluation']}};
$$('[data-resource]').forEach(b=>b.addEventListener('click',()=>{const r=resources[b.dataset.resource],url=safeUrl(site?.[r.key]);if(url){window.open(url,'_blank','noopener,noreferrer');return;}showInfo(r.title,`<p>${r.body}</p><ul>${r.details.map(x=>`<li>${x}</li>`).join('')}</ul><p class="source-note">Release planned. No external service is connected in this local preview.</p>`);}));
$('#submission-button').addEventListener('click',()=>{const url=safeUrl(site?.submissionUrl);if(url){window.open(url,'_blank','noopener,noreferrer');return;}showInfo('Bring your simulator to the arena.',`<p>Community submissions are not yet open. The current leaderboard is a snapshot of the paper’s results.</p><p>The planned submission package will identify the model, observation modality, evaluation setting, benchmark version, and reproducible evaluation artifacts. Ranking and review policies will be published with the submission service.</p><p class="source-note">Download a draft metadata template for planning. It is not an official evaluation contract and does not submit anything.</p><button class="button primary" id="download-template">Download draft template ↓</button>`,'COMMUNITY / COMING SOON');$('#download-template').addEventListener('click',()=>download('userarena-submission-draft.json',JSON.stringify({schemaVersion:'draft-0.1',status:'not-submitted',model:{name:'',version:'',modality:null},setting:null,benchmarkVersion:null,metrics:Object.fromEntries(keys.map(k=>[k,null])),artifacts:{evaluationReportUrl:null,codeUrl:null},note:'Planning template only. Official submission protocol is pending.'},null,2)));});
$('#copy-citation').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#citation-text').textContent);toast('BibTeX copied. Anonymous manuscript citation.');}catch{showInfo('Copy the citation','<p>Clipboard access is unavailable. Select and copy the citation below.</p><pre class="copy-fallback"></pre>');$('.copy-fallback').textContent=$('#citation-text').textContent;}});
async function loadJson(url){const r=await fetch(url);if(!r.ok)throw new Error('Could not load '+url);return r.json();}
try{
 [site,trajectories,results]=await Promise.all([loadJson('data/site.json'),loadJson('data/trajectories.json'),loadJson('data/leaderboard.json')]);renderTrajectory();renderLeaderboard();
 if(safeUrl(site.codeUrl))$$('[data-code-link]').forEach(a=>a.href=safeUrl(site.codeUrl));
 $$('[data-resource]').forEach(b=>{if(safeUrl(site[resources[b.dataset.resource].key])){const status=b.querySelector('.resource-status');if(status){status.textContent='Explore release ↗';status.classList.add('available');}if(b.dataset.resource==='environment')b.innerHTML='Launch environment <span aria-hidden="true">↗</span>';}});
 if(safeUrl(site.demoVideoUrl)){const video=document.createElement('video');video.controls=true;video.preload='metadata';video.src=safeUrl(site.demoVideoUrl);video.className='demo-video';video.setAttribute('aria-label','UserArena environment demonstration');$('#explore .environment-callout').after(video);}
}catch(error){console.error(error);toast('Interactive data could not load. Refresh using the local preview server.');$('#leaderboard-body').innerHTML='<tr><td colspan="13">Results could not load. Read Table 2 in the paper or refresh.</td></tr>';$('#timeline').innerHTML='<li>Trajectory data could not load. Please refresh.</li>';$$('#explore button, #leaderboard button, #leaderboard select').forEach(b=>b.disabled=true);}
